micronaut:
  server:
    cors:
      enabled: true
      configurations:
        allowedOrigins:
          - '*'
        exposedHeaders:
          - Content-Type
          - Authorization
          - '*'
      single-header: true
  application:
    name: extractor-CE
endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
jackson:
  serialization:
    writeDatesAsTimestamps: false

hazelcast:
  enabled: false

ingestion:
  topicPattern: extractor.raw.{collection}.{topic}

kafka:
  enabled: true
  embedded: true
  bootstrapServers: localhost:9092

logger:
  topic: extractor.events.log
  partitions: 50

repository:
  topic: extractor.repositories
  partitions: 16

metrics:
  topic: extractor.metrics
  partitions: 50